export const publicEnv = {
  networkLabel: process.env.NEXT_PUBLIC_NETWORK_LABEL ?? "",
  chainId: process.env.NEXT_PUBLIC_CHAIN_ID ?? "",
  walletConnectProjectId: process.env.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID ?? "",
  treasurySafeAddress: process.env.NEXT_PUBLIC_TREASURY_SAFE_ADDRESS ?? "",
  signalSinkAddress: process.env.NEXT_PUBLIC_SIGNAL_SINK_ADDRESS ?? "",
  reputationRegistryAddress: process.env.NEXT_PUBLIC_REPUTATION_REGISTRY_ADDRESS ?? "",
  pulseTokenAddress: process.env.NEXT_PUBLIC_PULSE_TOKEN_ADDRESS ?? "",
  pulseRegistryAddress: process.env.NEXT_PUBLIC_PULSE_REGISTRY_ADDRESS ?? "",
  identityRegistryAddress: process.env.NEXT_PUBLIC_IDENTITY_REGISTRY_ADDRESS ?? "",
  baseRpcUrl: process.env.NEXT_PUBLIC_BASE_RPC_URL ?? "",
  erc8004RegisterUrl: process.env.NEXT_PUBLIC_ERC8004_REGISTER_URL ?? "",
  pulseFeedUrl: process.env.NEXT_PUBLIC_PULSE_FEED_URL ?? "",
  explorerTxBaseUrl: process.env.NEXT_PUBLIC_EXPLORER_TX_BASE_URL ?? "",
  lastRunStatus: process.env.NEXT_PUBLIC_LAST_RUN_STATUS ?? "",
  lastRunTs: process.env.NEXT_PUBLIC_LAST_RUN_TS ?? "",
  lastRunNetwork: process.env.NEXT_PUBLIC_LAST_RUN_NETWORK ?? "",
  lastRunLog: process.env.NEXT_PUBLIC_LAST_RUN_LOG ?? "",
  lastRunLabel: process.env.NEXT_PUBLIC_LAST_RUN_LABEL ?? "",
  aliveWindowSeconds: process.env.NEXT_PUBLIC_ALIVE_WINDOW_SECONDS ?? "",
  inboxKeyTtlSeconds: process.env.NEXT_PUBLIC_INBOX_KEY_TTL_SECONDS ?? "",
};
